services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    tmpfs:
      - /data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand({ ping: 1 })']
      interval: 2s
      timeout: 2s
      retries: 30
